### ISSUE TITLE
"Last added" in categoria Movies nu mai merge

### ISSUE THREAD

**Issue by fanelaru** [yokrysty/krysty-xbmc#12]
Problema este in default.py la linia 216. Din cauza modificarii paginii, parsarea nu mai extrage si anul. Anul e intr-un alt DIV, asa ca la linia 243 vom avea eroare.

Nu stiu Python asa ca am facut o corectie doar ca sa-mi mearga mie scriptul. Nu mai afisez anul intre paranteze ci dublez titlul :)

#year = re.findall('(\d{4,4})', ep_year)
name = '%s (%s)' % (title, title)

**Comment by yokrysty** [comment]
multumesc pentru semnalizare
problema apare din cauza filmelor care nu au anul specificat
rezolvare simpla:
   year = re.findall('(\d{4,4})', ep_year)
   year = year[0] if year else "unknown"
   name = '%s (%s)' % (title, year)

**Comment by fanelaru** [comment]
Fixed in 0.4.14
