### ISSUE TITLE
Youtube trailer pentru filme nu merge

### ISSUE THREAD

**Issue by fanelaru** [yokrysty/krysty-xbmc#13]
Functia youtube_video(url) linia 425 trebuie scos spatiul ala de dupa "url_encoded_fmt_stream_map":

Linia trebuie sa arate asa:

s = re.findall(r'"url_encoded_fmt_stream_map":"([^"]+)"', content)

**Comment by yokrysty** [comment]
multumesc pentru semnalizare, dar cred ca o solutie mai buna ar fi:
s = re.findall(r'"url_encoded_fmt_stream_map": ?"([^"]+)"', content)
in cazul in care mai exista pagini cu acel spatiu

**Comment by fanelaru** [comment]
Fixed in 0.4.14
