### ISSUE TITLE
Plugin metadata 

### ISSUE THREAD

**Issue by retardone** [yokrysty/krysty-xbmc#14]
Salut,

Crezi ca poti prinde in plugin si partea de metadata? Atat pentru filme cat si pentru seriale?

Multumesc,

**Comment by yokrysty** [comment]
am vrut de multe ori sa includ, dar influenteaza in mod negativ viteza de incarcare
am vrut sa pastrez plugin-ul cat mai compact si rapid
nu stiu daca multi au nevoie de metadata

**Comment by retardone** [comment]
Ok, multumesc. Poate-l incluzi totusi, eventual cu optiune prin setari (Metadata On/Off).

O zi buna!
