### ISSUE TITLE
Episoadele serialelor de pe 990.ro nu pot fi rulate.

### ISSUE THREAD

**Issue by abiit** [yokrysty/krysty-xbmc#15]
Salut,
In primul rand iti multumesc foarte mult pentru munca depusa in scopul mentinerii plugin-ului pentru 990.ro; este printre putinele pe care le folosesc in mod curent pentru vizionarea de seriale. 
De vreo cateva zile, in XBMC/KODI, plugin-ul nu reuseste sa redea nimic din sectiunea seriale. Se incarca rapid sezoanele, episoadele se vad corect, dar in momentul in care incerc sa rulez un episod al oricarui serial imi este returnata eroarea: ”Video link(s) not available!”.
Acest lucru se intampla atat pe Minix neo X8-h Plus (in XBMC pentru minix), cat si pe Fire TV Stick (pe care am instalat Kodi 15.1).
Ar fi extraordinar daca s-ar putea face ceva in aceasta privinta.
Inca o data, multumesc frumos!

**Comment by oof3be** [comment]
Episoadele le vede, numai că link-urile s-au modificat.
M-am uitat puțin pe cod 
Row 145 : tvshow['url'] = siteUrl + 'player-serial-' + episodes[current][1] + '-sfast.html'
Link-ul aici nu mai arată așa ci mai conține încă un număr pe care probabil trebuie făcut match.
De exemplu -sfast-[\d+].html.

**Comment by zodrach** [comment]
Intr-adevar de cca 2 zile nu mai merg serialele nici pe 990 si nici pe cinemaxx.

**Comment by Sobica** [comment]
Vin eu cu o solutie, nu tocmai frumusica pentru ca asta a fost "botezul" meu in python :) si pe deasupra ma si grabeam sa ma intorc la serialul meu :)
Nu ma injurati, este doar o solutie temporara pana cand pluginul este updatat.

In "default.py" cauta functia getEpisodes:

```python
def getEpisodes(url,season,title,thumbnail):
	progress = xbmcgui.DialogProgress()
	progress.create('Progress', 'Please wait...')
	progress.update(1, "", "Loading list - 1%", "")

	title = re.sub('\(.+?\)', '', title).strip()
	
	list = []
	
	cache = False
	if plugin.getSetting("enableCache") == 'true':
		cacheFilename = '%s-s%s-episodes' % (re.sub(' ', '-', title), season)
		cache = plugin.cacheLoad(cacheFilename, int(plugin.getSetting("cacheExpire")))
		if cache:
			list = cache

	if not cache:		
		div = htmlFilter(str(BeautifulSoup(http_req(url)).find("div", {"id": "content"})), True)
		
		episodes = re.findall(r'Sezonul '+season+', Episodul (.+?)</div>.+?<a href="seriale2-([\d]+-[\d]+)-.+?.html" class="link">(.+?)</a>', div)
		#Adauga asta
		linkuri = re.findall(r'Sezonul '+season+', Episodul (.+?)</div>.+?<a href="(.+?)" class="link">(.+?)</a>', div)

		if episodes:
			total = len(episodes)
		else:
			episodes = re.findall(r'ma;">([\d]+)</div>.+?<a href="seriale2-([0-9]+-[0-9]+)-.+?.html" class="link">(.+?)</a>', div)
			#Adauga asta
			linkuri = re.findall(r'ma;">([\d]+)</div>.+?<a href="(.+?)" class="link">(.+?)</a>', div)
			total = len(episodes)

		current = 0

		while current <= total - 1:
			
			ep_num = episodes[current][0]
			ep_name = episodes[current][2]
			
			if ep_name == str(re.findall('(Episodul [-0-9]*)',ep_name)).strip('[]').strip('"\''): ep_name = ''
			
			#Adauga urmatoarele 2 linii
			unde = siteUrl + linkuri[current][1]
			lnk = iaLink(unde)

			tvshow = {}
			#tvshow['url'] = siteUrl + 'player-serial-' + episodes[current][1] + '-sfast.html'
			#schimbam url
			tvshow['url'] = siteUrl + lnk
			tvshow['thumbnail'] = thumbnail
			tvshow['title'] = title
			tvshow['season'] = season
			tvshow['ep_num'] = ep_num
			tvshow['ep_name'] = ep_name
			list.append(tvshow)
			
			if progress.iscanceled(): sys.exit()
			
			percent = int(((current + 1) * 100) / total)
			message = "Loading list - " + str(percent) + "%"
			progress.update(percent, "Enabling cache storage will speed up future loads.", message, "")
			
			current += 1
			
		if plugin.getSetting("enableCache") == 'true':
			plugin.cacheList(list, cacheFilename)

	for tvshow in list:
		name = 'Episode %s %s' % (tvshow['ep_num'], tvshow['ep_name'])
		
		addDir(name,tvshow['url'],8,tvshow['thumbnail'],tvshow['title'],tvshow['season'],tvshow['ep_num'],tvshow['ep_name'],folder=False)
		
	progress.close()

	xbmcplugin.endOfDirectory(int(sys.argv[1]))
	
#Adauga functie noua
def iaLink(url):
	div = htmlFilter(str(BeautifulSoup(http_req(url)).find("div", {"id": "content"})), True)
	link = re.findall(r'<a class="link" href="(.+?)" rel="nofollow" target="_blank">', div)
	return link[0]
```

**Comment by abiit** [comment]
Salut,

@Sobica Am incercat sa modific conform indicatiilor fisierul ”default.py”, insa pare-se ca-mi fug prea tare ochii. Ai putea sa urci numai acest fisier completat corespunzator, astfel incat sa-l actualizam pe cel din arhiva zip a plugin-ului?
Mersi!

**Comment by yokrysty** [comment]
Salutare, am fost ocupat si nu am apucat sa mai verific plugin-ul, dar acum am ceva timp liber si voi incarca update-ul cat mai repede.

**Comment by Sobica** [comment]
@abiit Pana reuseste Krysty sa faca update-ul (Multumim pentru plugin pe calea asta) fisierul este aici:
https://www.dropbox.com/s/xcx5lkm41er94q6/default.rar?dl=1

Dupa ce-l extragi din arhiva il inlocuiesti cu cel din:
```
[kodi path]\addons\plugin.video.990
```

**Comment by abiit** [comment]
Functioneaza, dar au aparut alte doua probleme (prima mai mare, iar a doua relativ neglijabila):
1) nu este afisata subtitrarea;
2) incarcarea sezoanelor este mai lenta.
In orice caz, multumesc mult pentru efort si bunele intentii domnule Sobica. 
Astept cu speranta si interventia creatorului original al plugin-ului.

**Comment by Sobica** [comment]
Încărcarea mai lenta este din cauza ca atunci când este încărcată lista de episoade, pt fiecare episod citește pagina acestuia... Imi cer scuze dar asta a fost soluția mea rapida, creatorul original o sa modifice probabil modul in care sunt afișate episoadele si o sa dispară aceasta problema....

Desprea partea cu subtitrarea... Nu știu de la ce este, la mine apare, încearcă sa dai un "Clear Cache" din meniul principal al plugin-ului

**Comment by yokrysty** [comment]
Problemele au fost rezolvate in versiunea 0.4.15.
Va multumesc tuturor pentru sprijin.

**Comment by abiit** [comment]
@Sobica 
Incarcarea listei cu episoade nu este deranjanta (cel putin pe Minix, care are un hardware destul de potent). Pentru remedierea problemei legate de subtitrare, stergerea cache-ului a fost prima operatiune pe care am facut-o, dar nu a functionat. Cu putine momente in urma am redeschis mediaplayer-ul si, voila, subtitrarea a aparut. Aparent, este necesara si o repornire. In concluzie, solutia propusa de tine este binevenita si rezolva complet problema din titlul topicului. Multumesc!
De asemenea, ii multumesc si lui Krysty care, cu siguranta, va veni cu o noua versiune a plugin-ului, functionala si accesibila tuturor...
Ah, tocmai a revenit!
Si noi multumim pentru operativitate si intelegere! :)

**Comment by zodrach** [comment]
sorry, dar nu merge inca. Imi apare aceeasi eroare.

**Comment by abiit** [comment]
@zodrach 
Dupa instalarea noii versiunii a plugin-ului, incearca ”clear cache” si/sau restartarea mp-ului. La mine functioneaza totul foarte bine.
