### ISSUE TITLE
Video link not available

### ISSUE THREAD

**Issue by razvanu** [yokrysty/krysty-xbmc#17]
Version 15 it's working for links, but the is no auto downloading subtitles. I can live with that :)

**Comment by Chiosc** [comment]
I have the same problem. :(

**Comment by sasa70** [comment]
version 16 not working for links

**Comment by yokrysty** [comment]
subtitle problem was fixed in version 0.4.16

**Comment by yokrysty** [comment]
all problems were fixed in version 0.4.17

download from https://github.com/yokrysty/krysty-xbmc

**Comment by razvanu** [comment]
Thank you
