### ISSUE TITLE
Te rog..iar da mesajul video link not availiblel

### ISSUE THREAD

**Issue by mikke75** [yokrysty/krysty-xbmc#19]
A mers perfect pana ieri cand am incercat sa vad un episod din serialul meu preferat a aparut mesajul video link not availble. Am incercat si alte seriale si apare acelasi mesaj. Multumesc pt munca depusa de a face 990 functionabil. Merge uns pe kodi 15.2 raspberry Pi

**Comment by mikke75** [comment]
Ok..pe naiba...acum merge dar nu mai merg subtitrarile

**Comment by mikke75** [comment]
Acum merge perfect cu tot cu subtitrari. Pe naiba...ba merge...ba nu merge. E bine ca acum merge

**Comment by yokrysty** [comment]
se poate sa fie problema de la site-ul 990.ro, sa fie "down"

**Comment by mikke75** [comment]
Ok. Multumesc. Daca as avea posibilitatea as face o donatie. Daca imipoti da amanunte...te rog

**Comment by yokrysty** [comment]
pe pagina principala este butonul de "donate" prin paypal
https://github.com/yokrysty/krysty-xbmc

**Comment by mikke75** [comment]
Salut Cristi. Nu mai merg subtitrarile pe varianta 0.4.18
