### ISSUE TITLE
990 pe Android 

### ISSUE THREAD

**Issue by mihaip1948** [yokrysty/krysty-xbmc#23]
Salut !
Am facut un test complet pe Android si am gasit urmatoarele probleme
- daca aleg Movies nu merge decat Recently added ... by Year si Genre nu !
- dupa ce obtin o lista de filme afiseaza doar o pagina ! si nu pot continua
- la seriale aceasi problema ... se afiseaza doar prima pagina din lista

**Comment by yokrysty** [comment]
salut!, acum am testat, la mine merge ok partea de seriale, iar la aceeasi problema descrisa de tine, voi verifica

**Comment by mihaip1948** [comment]
Cred ca n-am fost suficient de explicit ...
- Movies ... By Year si By Genre ... returneza o lista vida 
- lista de filme sau seriale returnata la Recently added are doar o pagina ! 
dar in realitate ea ar trebui sa continue 
- astazi dimineatza n-am putut relua testul deoarece si la Movies si la TV Shows
pe Recently added ... Error : something went wrong ! ... sistematic

**Comment by yokrysty** [comment]
acum am inteles ce zici, lista returnata la Recently Added, are doar o pagina, la setari exista o optiune unde poti alege cate randuri vor fi afisate la Recently Added (default este 15, maxim 30), am facut astfel pentru a fi mai rapida incarcarea listei cand se foloseste metadata.

**Comment by mihaip1948** [comment]
Aha ... OK ! asta e ! poti face ceva pe Android cu selectiile By Year si By Genre ?

**Comment by yokrysty** [comment]
ok, voi pune o limita mai mare, nu am facut cu NEXT PAGE pentru ca pe site nu sunt mai multe pagini, legat de Year, Genre, lucrez la asta, dar nu prea am timp liber si va dura ceva

**Comment by yokrysty** [comment]
se pare ca am reusit sa rezolv problema mai repede decat am anticipat, te rog sa incerci versiunea 0.5.2 si sa imi spui daca mai exista probleme, la mine totul este ok

**Comment by mihaip1948** [comment]
Felicitari ! tot ce am verificat ... dimineatza la prima vedere este OK !
le dau baietilor pe forum sa sape si ei ... sa vedem ! inca odata ...
multzam !

**Comment by yokrysty** [comment]
:) ma pun sa dorm asa tarziu ca am mult de lucru si cand mai fac pauze mai lucrez si la acest plugin
