### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12

### ISSUE THREAD

**Issue by csmodfw** [yokrysty/krysty-xbmc#24]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)

Fix add unicode for title
        title = htmlFilter(a.text)
        title = unicode(title, 'utf-8')
        url = urlFilter(a['href'])

**Comment by yokrysty** [comment]
the problem is from the return value of regular expressions, which is unicode and title is str, after string format the result is unicode, so the simple solution is to convert the return value from re into str
            year = re.search('(\d{4,4})', ep_year)
            year = str(year.group(1)) if year else 'unknown'
            name = '%s (%s)' % (title, year)

**Comment by csmodfw** [comment]
search not work witch accent ex: Bélier. have to show La Famille Bélier
