### ISSUE TITLE
Info calitate video in 0.5.2 cum era si in 0.4.x

### ISSUE THREAD

**Issue by fanelaru** [yokrysty/krysty-xbmc#25]
Se poate introduce si informatia despre calitatea video in 0.5.x? Acum cind dai click pe film iti apar doar sursele.

**Comment by yokrysty** [comment]
se afiseaza si calitatea: titlul ferestrei surselor, am facut un print screen in care se poate observa
http://postimg.org/image/5br463ox3/full/

**Comment by fanelaru** [comment]
Mea culpa! Era acolo!

#closed
