### ISSUE TITLE
990 sub Enigma2

### ISSUE THREAD

**Issue by mihaip1948** [yokrysty/krysty-xbmc#26]
Salut Krysty !
am instalat plugin.video.990   0.5.2 pe un receptor satelit cu Enigma2 chipset Broadcom ...
 cu un pic de ajutor ... merge ! si inca chiar foarte bine ! dar are doua ciudatenii  

- dupa selectia filmului nu-mi mai apare lista surselor ... probabil ca alege automat  prima 
sursa ca porneste si merge la fix
- nu pot intra in sectiunea de settings ... ramane undeva in python si bucleaza asteptant 
un eveniment ... dau EXIT si abandoneaza .... probabil din nou o specialitate de Python !

Sub Android si pe Win10 ambele aspecte sesizate sunt functionale !

**Comment by yokrysty** [comment]
nu stiu ce sa zic, nu am posibilitatea de a testa pe astfel de dizpozitiv.
Ce versiune este Kodi sau XBMC?
Ai posibilitatea de a extrage log-ul, poate scrie ceva in momentul cand se blocheaza.

**Comment by mihaip1948** [comment]
Receptoarele satelit ruleaza sub un Linux peste care merge
aplicatia DVB numita Enigma2 ... sub Enigma2 ruleaza un
skin in care se implementeaza apelurile functionalitatilor
necesare dar si diverse pluginuri. Unul dintre aceste pluginuri
se numeste KodiDirect si este o implementare subset de
Kodi ... in KodiDirect se pot sinstala addonuri de genul 990  !
Skinul, KodiDirect si 990 sunt scrise toate in Python ... cred eu
ca versiunea 2.7 ... Unele addonuri se instaleaza si merg fara
nici o modificare ... altele trebuie ajutate ... manevra care se face
este inlocuirea modulului __init__.py cu unul cu mult mai multe
referinte ! dupa care totul este OK ... sau ma rog cu mici exceptii
legate de eventuale incompatibilitati de Python ! o sa incerc sa
scot un LOG ! sa vedem poate ajuta ... nu arde ! ca de pornit
porneste ! stiu ca-i complicata impacarea intre capra si varza ...

**Comment by yokrysty** [comment]
ok, am inteles cum sta treaba
cand voi avea timp voi incerca sa instalez Enigma2 pe Ubuntu in VMware, pentru a avea o platfrma de testare :)

**Comment by mihaip1948** [comment]
Pai ce sa zic ... va fi cam greu ! fiind dependent de harware ... poate
c-ar fi mai simplu sa-ti trimit un receptor cu un minim de instructiuni
de operare ... dealtfel pe partea de KodiDirect sunt chiar banale !
si asa poti face teste pe masura ce dezvolti ceva nou ! sa fac ceva
aranjamente si vorbim !

**Comment by mihaip1948** [comment]
Gata ! eu am un receptor pregatit pentru tine ! daca-l
doresti pentru a putea testa 990 sub Enigma2 ... da-mi
un mesaj cu adresa ta la : misup_misup@yahoo.com !!!

**Comment by yokrysty** [comment]
eu nu sunt in tara pana in data de 9 ianuarie 2016, vorbim cand revin :)

**Comment by mihaip1948** [comment]
Aha ... este in regula ! ramane dupa sarbatori ...

**Comment by mihaip1948** [comment]
Oferta este in continuare valabila !

**Comment by mihaip1948** [comment]
Repozitorul in care sta 990 0.5.4 nu are format corect ! nu pot sa-l incarc din    .zip !!!

**Comment by yokrysty** [comment]
cred ca este o problema pe windows-ul tau, eu am verificat la mai multi prieteni si merge
daca ai vechiul repository (repository.googlecode.krysty-xbmc) instalat, dezinstaleaza-l si mai sterge si fisierul/fsierele Addons#.db (3 - un numar) din C:\Users\#USER-UL TAU#\AppData\Roaming\Kodi\userdata\Database

**Comment by mihaip1948** [comment]
A fost greseala mea ! am instalat repozitorulam dat jos vechea versiune ...si s-a instalat corect !parca merge ceva mai incet !

**Comment by yokrysty** [comment]
versiunea 0.5.4 este mai rapida, daca pastrezi metadata pe Off

**Comment by mihaip1948** [comment]
Sub Enigma2 5.04 nu mai trece de lista filmelor ! dau OK pe un
film si ramane intr-o bucla Python ... precis este vb de o constructie
nesuportata in Python 2.7.3 ...ca asta este acolo

**Comment by yokrysty** [comment]
hmm, de la 0.5.2 la 0.5.4 nu sunt diferente mari in cod, nu stiu de ce nu ar merge, in log apare ceva?

**Comment by mihaip1948** [comment]
S-a rezolvat ! omul recompileaza cu un __init__.py nou ...
si porneste sistematic !
