### ISSUE TITLE
Lipsa subtitrari pe varianta 0.4.18

### ISSUE THREAD

**Issue by mikke75** [yokrysty/krysty-xbmc#27]
Salut si Craciun fericit! Subtitrarile pe 990 var. 0.4.18 de ieri au disparut.

**Comment by dab78** [comment]
Ai dreptate mikke75 nu îmi merg nici mie subtitrarile.

**Comment by fanelaru** [comment]
Nici pe 0.5.2 nu mai funcționează. Workaround: plugin opensubtitles.org.

**Comment by dab78** [comment]
Poate apare alta versiune.☺
