### ISSUE TITLE
cinemarx se pare ca a inviat

### ISSUE THREAD

**Issue by fanelaru** [yokrysty/krysty-xbmc#29]
Din pacate 1.0.11 nu mai merge:

11:00:10 T:3448  NOTICE: cinemaxx.ro: Loading sqlite3 as DB engine version: 3.8.6
11:00:10 T:3448  NOTICE: plugin.video.cinemaxx v1.0.11
11:00:10 T:3448  NOTICE: cinemaxx.ro: All tables have been successfully loaded.
11:00:10 T:3448  NOTICE: Mode: 3
11:00:10 T:3448  NOTICE: URL: http://www.cinemaxx.rs/the-little-prince-2015_63ba8efc3.html
11:00:17 T:5268   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.cinemaxx/?mode=3&name=The%20Little%20Prince%20(2015)&thumbnail=http%3a%2f%2fwww.cinemaxx.rs%2fuploads%2fthumbs%2f63ba8efc3-1.jpg&url=http%3a%2f%2fwww.cinemaxx.rs%2fthe-little-prince-2015_63ba8efc3.html
11:00:17 T:5268   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cinemaxx/?mode=3&name=The%20Little%20Prince%20(2015)&thumbnail=http%3a%2f%2fwww.cinemaxx.rs%2fuploads%2fthumbs%2f63ba8efc3-1.jpg&url=http%3a%2f%2fwww.cinemaxx.rs%2fthe-little-prince-2015_63ba8efc3.html) failed
11:00:17 T:10660  NOTICE: Thread BackgroundLoader start, auto delete: false
11:00:17 T:5268  NOTICE: DVDPlayer: Opening: http://217.20.157.211/?sig=e34ab04ad9b8b7fa70d051fcaf52d5f4c59b024d&ct=0&urls=217.20.153.69%3B217.20.157.209%3B217.20.145.46&expires=1451552413789&srcIp=78.97.93.3&srcAg=CHROME&clientType=0&id=71775226586&type=2|User-Agent=Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36&Accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8&Referer=http%3A%2F%2Fwww.cinemaxx.rs%2F
11:00:17 T:5268 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
11:00:17 T:2760  NOTICE: Thread DVDPlayer start, auto delete: false
11:00:17 T:2760  NOTICE: Creating InputStream
11:00:17 T:2760   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://217.20.157.211/?sig=e34ab04ad9b8b7fa70d051fcaf52d5f4c59b024d&ct=0&urls=217.20.153.69%3B217.20.157.209%3B217.20.145.46&expires=1451552413789&srcIp=78.97.93.3&srcAg=CHROME&clientType=0&id=71775226586&type=2|User-Agent=Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36&Accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8&Referer=http%3A%2F%2Fwww.cinemaxx.rs%2F
11:00:18 T:2760   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
11:00:18 T:2760   ERROR: CCurlFile::Open failed with code 400 for http://217.20.157.211/?sig=e34ab04ad9b8b7fa70d051fcaf52d5f4c59b024d&ct=0&urls=217.20.153.69%3B217.20.157.209%3B217.20.145.46&expires=1451552413789&srcIp=78.97.93.3&srcAg=CHROME&clientType=0&id=71775226586&type=2|User-Agent=Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36&Accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8&Referer=http%3A%2F%2Fwww.cinemaxx.rs%2F
11:00:18 T:2760   ERROR: XFILE::CFileCache::Open - failed to open source <http://217.20.157.211/?sig=e34ab04ad9b8b7fa70d051fcaf52d5f4c59b024d&ct=0&urls=217.20.153.69%3B217.20.157.209%3B217.20.145.46&expires=1451552413789&srcIp=78.97.93.3&srcAg=CHROME&clientType=0&id=71775226586&type=2|User-Agent=Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36&Accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8&Referer=http%3A%2F%2Fwww.cinemaxx.rs%2F>
11:00:18 T:2760   ERROR: CDVDPlayer::OpenInputStream - error opening [http://217.20.157.211/?sig=e34ab04ad9b8b7fa70d051fcaf52d5f4c59b024d&ct=0&urls=217.20.153.69%3B217.20.157.209%3B217.20.145.46&expires=1451552413789&srcIp=78.97.93.3&srcAg=CHROME&clientType=0&id=71775226586&type=2|User-Agent=Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36&Accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8&Referer=http%3A%2F%2Fwww.cinemaxx.rs%2F]
11:00:18 T:2760  NOTICE: CDVDPlayer::OnExit()
11:00:18 T:5268  NOTICE: CDVDPlayer::CloseFile()
11:00:18 T:5268  NOTICE: DVDPlayer: waiting for threads to exit
11:00:18 T:5268  NOTICE: DVDPlayer: finished waiting
11:00:18 T:5268  NOTICE: CDVDPlayer::CloseFile()
11:00:18 T:5268  NOTICE: DVDPlayer: waiting for threads to exit
11:00:18 T:5268  NOTICE: DVDPlayer: finished waiting
11:00:18 T:11836  NOTICE: cinemaxx.ro: Playback Stopped
11:00:18 T:11836  NOTICE: cinemaxx.ro: Service: Resetting...

**Comment by yokrysty** [comment]
am rezolvat in versiunea 1.0.12, se pare ca cei de la ok.ru au mai adaugat un header obligatoriu in plus (Origin) :))))

**Comment by fanelaru** [comment]
Verific si inchid tichetul

Merci

**Comment by fanelaru** [comment]
Se pare ca arhiva cu 1.0.12 e invalida. Nu o pot deschide nici cu 7zip.

**Comment by yokrysty** [comment]
este ok, am verificat, instalaleaza, te rog, repository-ul pentru auto update

**Comment by fanelaru** [comment]
Hmmm.... Mi-e teama ca nu stiu cum sa instalez repository-ul pentru auto-update. Sunt aceeasi pasi dati de srp.nu (superrepo)? . 
Oricum, am rezolvat, am facut un git pull si l-am luat de acolo, Daca dau click dreapta din Chrome si download imi descarca 33 KB. La git pull, in schimb, imi aduce arhiva corect.

Multumesc.
