### ISSUE TITLE
Nu pot adauga subtitrari locale

### ISSUE THREAD

**Issue by zodrach** [yokrysty/krysty-xbmc#32]
Am incercat si pe alte plugin-uri si acolo merge(icefilm, filmehd, genesis...). In 990 cand incerc sa adaug o subtitrare de pe local ramane blocat in "working" fara a afisa locatia setata pentru subtitrari locale.

**Comment by yokrysty** [comment]
pe ce versiune de plugin ai incercat? am incercat pe 0.5.3 si nu sunt probleme.

PS: pentru subtitrari iti recomand plugin-ul service.subtitles.opensubtitles, l-am inclus si eu in repository

**Comment by zodrach** [comment]
sunt pe 0.5.3 si eu si am si opensubtitles tot de aici. La fel pe 2 pc-uri si pe o tableta

**Comment by yokrysty** [comment]
Poti posta log-ul si un printscreen ?

**Comment by zodrach** [comment]
11:18:29 T:6416  NOTICE: Thread LanguageInvoker start, auto delete: false
11:18:29 T:6416  NOTICE: -->Python Interpreter Initialized<--
11:18:29 T:6416  NOTICE: plugin.video.990: v0.5.3
11:18:29 T:6416  NOTICE: plugin.video.990: Loading sqlite3 as DB engine, version: 3.8.6
11:18:29 T:6416  NOTICE: plugin.video.990: metahandler: Initializing MetaHandlers version: 2.9.0
11:18:29 T:6416  NOTICE: plugin.video.990: metahandler: Loading sqlite3 as DB engine version: 3.8.6
11:18:29 T:6416  NOTICE: plugin.video.990: All tables have been successfully loaded.
11:18:29 T:6416  NOTICE: plugin.video.990: ------------------PARAMS------------------
11:18:29 T:6416  NOTICE: plugin.video.990: --- Mode: 1
11:18:29 T:6416  NOTICE: plugin.video.990: --- Url: http://www.990.ro/seriale2-265666-29591-Dickensian-Episodul-6-online.html
11:18:29 T:6416  NOTICE: plugin.video.990: --- Name: Dickensian
11:18:29 T:6416  NOTICE: plugin.video.990: --- Thumbnail: DefaultVideo.png
11:18:29 T:6416  NOTICE: plugin.video.990: --- Video Type: episode
11:18:29 T:6416  NOTICE: plugin.video.990: --- TV Show Name:
11:18:29 T:6416  NOTICE: plugin.video.990: --- Year:
11:18:29 T:6416  NOTICE: plugin.video.990: --- Season: 01
11:18:29 T:6416  NOTICE: plugin.video.990: --- Episode: 06
11:18:29 T:6416  NOTICE: plugin.video.990: --- Episode Name:
11:18:29 T:6416  NOTICE: plugin.video.990: --- IMDB ID:
11:18:29 T:6416  NOTICE: plugin.video.990: --- TV Show Thumbnail:
11:18:29 T:6416  NOTICE: plugin.video.990: ------------------------------------------
11:18:29 T:6416  NOTICE: plugin.video.990: metahandler: Table movie_meta initialized
11:18:29 T:6416  NOTICE: plugin.video.990: metahandler: Table tvshow_meta initialized
11:18:29 T:6416  NOTICE: plugin.video.990: metahandler: Table season_meta initialized
11:18:29 T:6416  NOTICE: plugin.video.990: metahandler: Table episode_meta initialized
11:18:29 T:6416  NOTICE: plugin.video.990: metahandler: Table addons initialized
11:18:29 T:6416  NOTICE: plugin.video.990: metahandler: Table config initialized
11:18:32 T:6816  NOTICE: DVDPlayer: Opening: http://sv11.fastupload.ro/download/0c275ad689d3797779617693163462f3/568e2d65/mp4/65d59e72649feb8209f9aa8bc7ee85df.mp4|referer=http://superweb.rol.ro/video/1/65d59e72649feb8209f9aa8bc7ee85df.html
11:18:32 T:6816 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
11:18:32 T:2888  NOTICE: Thread DVDPlayer start, auto delete: false
11:18:32 T:2888  NOTICE: Creating InputStream
11:18:33 T:2888  NOTICE: Creating Demuxer
11:18:33 T:2384  NOTICE: Thread FileCache start, auto delete: false
11:18:34 T:2888  NOTICE: Opening stream: 0 source: 256
11:18:34 T:2888  NOTICE: Creating video codec with codec id: 28
11:18:34 T:2888  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
11:18:34 T:2888  NOTICE: Creating video thread
11:18:34 T:2888  NOTICE: Opening stream: 1 source: 256
11:18:34 T:2888  NOTICE: Finding audio codec for: 86018
11:18:34 T:1676  NOTICE: Thread DVDPlayerVideo start, auto delete: false
11:18:34 T:1676  NOTICE: running thread: video_thread
11:18:34 T:2888  NOTICE: Creating audio thread
11:18:34 T:5172  NOTICE: Thread DVDPlayerAudio start, auto delete: false
11:18:34 T:5172  NOTICE: running thread: CDVDPlayerAudio::Process()
11:18:34 T:1676   ERROR: CDVDVideoCodecFFmpeg::Decode - avcodec_decode_video returned failure
11:18:34 T:1676  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(720x404)
11:18:34 T:5172  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
11:18:34 T:5172  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
11:18:34 T:1676  NOTICE:  fps: 25.000000, pwidth: 720, pheight: 404, dwidth: 720, dheight: 404
11:18:34 T:1676  NOTICE: Display resolution DESKTOP : 1680x1050@ 59.94 - Full Screen (16)
11:18:34 T:1676  NOTICE: D3D: rendering method forced to DXVA processor
11:18:34 T:6816 WARNING: CWinRenderer::UpdateVideoFilter - chosen scaling method 1 is not supported by renderer
11:18:34 T:1280  NOTICE: 990.ro: Service: Playback started
11:18:34 T:1280  NOTICE: 990.ro: Service: Tracking progress...
11:18:34 T:5172  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
11:18:34 T:5172  NOTICE: Previous line repeats 3 times.
11:18:34 T:5172 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available
11:18:35 T:5172  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
11:18:35 T:5172  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 4 packets of duration 21
11:18:35 T:5172  NOTICE: Previous line repeats 2 times.
11:18:35 T:5172  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
11:18:35 T:5172  NOTICE: Previous line repeats 7 times.
11:18:35 T:5172 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available
11:18:35 T:4960  NOTICE: cinemaxx.ro: Service: Playback started
11:18:35 T:5172 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available
11:18:36 T:5172  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 4 packets of duration 21
11:18:47 T:1676  NOTICE: Previous line repeats 3 times.
11:18:47 T:1676 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
11:19:18 T:3088 WARNING: Previous line repeats 1 times.
11:19:18 T:3088  NOTICE: Thread JobWorker start, auto delete: true
11:19:44 T:6816   ERROR: XFILE::CDirectory::GetDirectory - Error getting multipath://http%3a%2f%2fsv11.fastupload.ro%2fdownload%2f0c275ad689d3797779617693163462f3%2f568e2d65%2fmp4%2f65d59e72649feb8209f9aa8bc7ee85df.mp4%7creferer%3dhttp%3a%2f%2fsuperweb.rol.ro%2fvideo%2f1%2f%7creferer%3dhttp%3a%2f%2fsuperweb.rol.ro%2fvideo%2f1%2f65d59e72649feb8209f9aa8bc7ee85df.html/H%3a%5c/
11:19:44 T:6816   ERROR: CGUIDialogFileBrowser::GetDirectory(multipath://http%3a%2f%2fsv11.fastupload.ro%2fdownload%2f0c275ad689d3797779617693163462f3%2f568e2d65%2fmp4%2f65d59e72649feb8209f9aa8bc7ee85df.mp4%7creferer%3dhttp%3a%2f%2fsuperweb.rol.ro%2fvideo%2f1%2f%7creferer%3dhttp%3a%2f%2fsuperweb.rol.ro%2fvideo%2f1%2f65d59e72649feb8209f9aa8bc7ee85df.html/H%3a%5c/) failed
11:19:50 T:1676 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
11:19:55 T:6816  NOTICE: CDVDPlayer::CloseFile()
11:19:55 T:6816  NOTICE: DVDPlayer: waiting for threads to exit
11:19:55 T:2888  NOTICE: CDVDPlayer::OnExit()
11:19:55 T:2888  NOTICE: Closing stream player 1
11:19:55 T:2888  NOTICE: Waiting for audio thread to exit
11:19:55 T:5172  NOTICE: thread end: CDVDPlayerAudio::OnExit()
11:19:55 T:2888  NOTICE: Closing audio device
11:19:55 T:2888  NOTICE: Deleting audio codec
11:19:55 T:2888  NOTICE: Closing stream player 2
11:19:55 T:2888  NOTICE: waiting for video thread to exit
11:19:55 T:1676  NOTICE: thread end: video_thread
11:19:55 T:2888  NOTICE: deleting video codec
11:19:55 T:2888  NOTICE: DXVA::CDecoder::Close - closing decoder
11:19:55 T:2888  NOTICE: DXVA::Close - closing decoder context
11:19:55 T:6816  NOTICE: DVDPlayer: finished waiting
11:19:55 T:1280  NOTICE: 990.ro: Playback Stopped
11:19:55 T:1280  NOTICE: 990.ro: Service: 01:20 played of 28:27, total = 4%
11:19:55 T:1280  NOTICE: 990.ro: Service: Threshold not met. Saving bookmark
11:19:56 T:2584  NOTICE: Thread BackgroundLoader start, auto delete: false
11:19:56 T:4960  NOTICE: cinemaxx.ro: Playback Stopped
11:19:56 T:4960  NOTICE: cinemaxx.ro: Service: Resetting...
11:19:56 T:6816  NOTICE: CDVDPlayer::CloseFile()
11:19:56 T:6816  NOTICE: DVDPlayer: waiting for threads to exit
11:19:56 T:6816  NOTICE: DVDPlayer: finished waiting
11:19:56 T:6816  NOTICE: CDVDPlayer::CloseFile()
11:19:56 T:6816  NOTICE: DVDPlayer: waiting for threads to exit
11:19:56 T:6816  NOTICE: DVDPlayer: finished waiting
11:19:56 T:7356  NOTICE: Thread JobWorker start, auto delete: true
11:19:56 T:1280  NOTICE: 990.ro: Service: Resetting...

**Comment by zodrach** [comment]
din logul de mai sus cred ca asta e:
11:19:44 T:6816 ERROR: XFILE::CDirectory::GetDirectory - Error getting multipath://http%3a%2f%2fsv11.fastupload.ro%2fdownload%2f0c275ad689d3797779617693163462f3%2f568e2d65%2fmp4%2f65d59e72649feb8209f9aa8bc7ee85df.mp4%7creferer%3dhttp%3a%2f%2fsuperweb.rol.ro%2fvideo%2f1%2f%7creferer%3dhttp%3a%2f%2fsuperweb.rol.ro%2fvideo%2f1%2f65d59e72649feb8209f9aa8bc7ee85df.html/H%3a%5c/
11:19:44 T:6816 ERROR: CGUIDialogFileBrowser::GetDirectory(multipath://http%3a%2f%2fsv11.fastupload.ro%2fdownload%2f0c275ad689d3797779617693163462f3%2f568e2d65%2fmp4%2f65d59e72649feb8209f9aa8bc7ee85df.mp4%7creferer%3dhttp%3a%2f%2fsuperweb.rol.ro%2fvideo%2f1%2f%7creferer%3dhttp%3a%2f%2fsuperweb.rol.ro%2fvideo%2f1%2f65d59e72649feb8209f9aa8bc7ee85df.html/H%3a%5c/) failed


Este eroarea pe care mi-o da mie atunci cand ii dau click dreapta(el fiind pe working)

**Comment by yokrysty** [comment]
am tot verificat si uneori se intampla sa dea o eroare si nu pot vedea discul local, dar daca intru din nou sa aleg titrarea functioneaza, pentru titrari eu folosesc plugin-ul opensubtitles

**Comment by zodrach** [comment]
tot opensubtitles folosesc si eu. Culmea este ca in directorul setat se duc subtitrarile cand le downloadez pt filmele care nu au.
