### ISSUE TITLE
Noua versiune

### ISSUE THREAD

**Issue by teapa** [yokrysty/krysty-xbmc#33]
Sa incep prin a va multumi pentru efortul facut in crearea acestui add on. Datorita lui parintii mei au reusit sa urmareasca cu usurinta filme traduse in romana (nu locuiesc in Romania). 

Deoarece nu mai mergeau subtitrarile la vechea versiune (4.6 cred) am instalat noua versiune 5.3. Acum in loc de un simplu ok trebuie sa alegi serverul dintr-o lista de 12, iar cind am incercat nici unul nu mergea. Cel putin imi puteti spune care server din lista are subtitrarile deja atasate ca inainte? Parintii mei nu stiu sa caute si ataseze subtitrarile. Multumesc.

**Comment by yokrysty** [comment]
in versiunea 0.4.19 a fost rezolvata problema subtitrarilor.

in versiunea veche era ales automat primul server (superweb), pentru ca nu am apucat sa implementez pentru celelalte, nici acum nu sunt toate functionale.
Titrarile in romana sunt valabile doar pe serverul superweb, dar atunci cand este folosit de multa lume, video-ul se incarca foarte greu. De aceea este bine sa existe si alte servere ca alternative, dar pe celelalte servere video-urile mai sunt sterse din cauza copyright-ului si nu tot timpul vor functiona, o alta problema ar fi calitatatea video, unele au o calitate mai proasta decat celelalte. Deocamdata sunt implementate serverele: gorillavid, daclips, vidbull, vodlocker, vidzi, acestea fiind functionale daca vide-ul nu a fost sters.
PS: pentru subtitrari recomand plugin-ul service.subtitles.opensubtitles.

Versiunea 0.5.x, este o versiune de test, mai am de lucrat pana va fi o versiunea finala.

Pentru a se incarca listele mai rapid, opriti din setari metadata.

Recomand sa instalati repository pentru update-uri automate.

**Comment by teapa** [comment]
multumesc
