### ISSUE TITLE
4.0.19

### ISSUE THREAD

**Issue by marieryro** [yokrysty/krysty-xbmc#34]
Am instalat asta 990.ro V  4.0.19. nu mai merge nimic pe 990.ro. da eroare si scrie ca nu gaseste link. Ce trebuie sa fac?

**Comment by marieryro** [comment]
video link is not available pe orice episod din seriale si pe orice film
iar versiune aceea cu 5.03 imi deschide o serie de linkuri de unde sa aleg si nu merge. Folosesc pe PC Kodi

**Comment by fanelaru** [comment]
Mda, iar s-a schimbat ceva la 990.ro

"Link not available" este mesajul si in 4.0.19 si in 5.0.3

**Comment by fanelaru** [comment]
18:36:59 T:1879947072   ERROR: InputStream: Error opening, plugin://plugin.video.990/?episode=13&name=Saving+Hope&url=http%3A%2F%2Fwww.990.ro%2Fseriale2-43816-29660-Saving-Hope-Goodbye-Girl-online.html&season=04&video_type=episode&mode=1&thumbnail=DefaultVideo.png
18:36:59 T:1879557944   ERROR: InputStream: Error opening, plugin://plugin.video.990/?episode=02&name=Shades+of+Blue&url=http%3A%2F%2Fwww.990.ro%2Fseriale2-251430-29661-Shades-of-Blue-Original-Sin-online.html&season=01&video_type=episode&mode=1&thumbnail=DefaultVideo.png
18:36:59 T:1879557944   ERROR: InputStream: Error opening, plugin://plugin.video.990/?episode=13&name=The+Big+Bang+Theory&url=http%3A%2F%2Fwww.990.ro%2Fseriale2-1055-29663-The-Big-Bang-Theory-The-Empathy-Optimization-online.html&season=09&video_type=episode&mode=1&thumbnail=DefaultVideo.png

**Comment by mikke75** [comment]
Nu merge. Link not availible

**Comment by Chiosc** [comment]
Dap, nu mai merge nici la mine. :(

**Comment by yokrysty** [comment]
updated

**Comment by marieryro** [comment]
Acum merge chiar perfect. Nu am mai update si  merge perfect. Chiar constat ca merge foarte repede, se incarca foarte repede. multumim.

**Comment by razvanu** [comment]
Thanks

**Comment by ursan2003** [comment]
Thanks man pentru munca depusa sa tii in picioare pluginul 990 si cinemaxx
Am o intrebare,ce sanse ar fi sa se poata face un plugin pentru Kodi la siteul
www.livetvonline.ro
Faza e ca aia ce au site-ul zic de ani de zile ca o sa merga pe android dar nici o speranta deci cred ca pentru android ramane ca unica solutie un plugin pentru Kodi
Thanks again

**Comment by yokrysty** [comment]
nu fac plugi-uri pentru site-urile care restrictioneaza numarul de utilizatori (verifica sa vezi ca nu poti crea un cont nou). dupa cum am timp si cand il voi termina pe cel pentru 990, urmatorul plugin va fi pentru filmehd.net.

**Comment by ursan2003** [comment]
Thanks pentru raspuns man
Ideea era sa vad daca  se poate face un plugin sa mearga in Kodi ,vorbind din prisma cuiva care se pricepe adica a ta
Inca o data multumiri pentru munca depusa

**Comment by yokrysty** [comment]
daca imi dai un cont pot incerca
