### ISSUE TITLE
livetvonline

### ISSUE THREAD

**Issue by derzis** [yokrysty/krysty-xbmc#35]
livetvonline nu merge pe linux. Se poate si pentru linux?

**Comment by yokrysty** [comment]
posteaza un log

**Comment by derzis** [comment]
17:49:51 T:140398278190848  NOTICE: -->Python Interpreter Initialized<--
17:49:53 T:140398278190848  NOTICE: plugin.video.livetvonline v1.0.1: XBMC/Kodi 15.1 (X11; Linux) plugin.video.livetvonline v1.0.1
17:49:53 T:140398278190848  NOTICE: plugin.video.livetvonline v1.0.1: ------------------PARAMS------------------
17:49:53 T:140398278190848  NOTICE: plugin.video.livetvonline v1.0.1: --- Mode: 0
17:49:53 T:140398278190848  NOTICE: plugin.video.livetvonline v1.0.1: --- Url:
17:49:53 T:140398278190848  NOTICE: plugin.video.livetvonline v1.0.1: --- Name:
17:49:53 T:140398278190848  NOTICE: plugin.video.livetvonline v1.0.1: --- Thumbnail:
17:49:53 T:140398278190848  NOTICE: plugin.video.livetvonline v1.0.1: ------------------------------------------
17:49:53 T:140398278190848   ERROR: GetDirectory - Error getting /home/derzis/.kodi/addons/plugin.video.livetvonline/resources/skins/default
17:49:53 T:140398278190848   ERROR: EXCEPTION: XML File for Window is missing
17:49:53 T:140398278190848   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XML File for Window is missing
                                            Traceback (most recent call last):
                                              File "/home/derzis/.kodi/addons/plugin.video.livetvonline/default.py", line 60, in <module>
                                                dialog = gui_utils.loginDialog()
                                              File "/home/derzis/.kodi/addons/plugin.video.livetvonline/gui_utils.py", line 92, in loginDialog
                                                return LoginDialog('LoginDialog.xml', common.addon_path, 'default', '720p')
                                            RuntimeError: XML File for Window is missing
                                            -->End of Python script error report<--
17:49:53 T:140400171743168   ERROR: GetDirectory - Error getting plugin://plugin.video.livetvonline/
17:49:53 T:140400171743168   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.livetvonline/) failed
17:49:53 T:140398278190848  NOTICE: Thread BackgroundLoader start, auto delete: false
17:53:08 T:140399757629184  NOTICE: Previous line repeats 3 times.
17:53:08 T:140399757629184  NOTICE: Thread JobWorker start, auto delete: true
17:53:11 T:140398294976256  NOTICE: Thread BackgroundLoader start, auto delete: false
17:53:20 T:140398294976256  NOTICE: Previous line repeats 3 times.
17:53:20 T:140398294976256  NOTICE: Thread JobWorker start, auto delete: true
17:53:37 T:140398956775168  NOTICE: Thread BackgroundLoader start, auto delete: false
17:54:07 T:140398956775168  NOTICE: Previous line repeats 3 times.
17:54:07 T:140398956775168  NOTICE: Thread LanguageInvoker start, auto delete: false
17:54:07 T:140398956775168  NOTICE: -->Python Interpreter Initialized<--
17:54:08 T:140398956775168  NOTICE: plugin.video.livetvonline v1.0.1: XBMC/Kodi 15.1 (X11; Linux) plugin.video.livetvonline v1.0.1
17:54:08 T:140398956775168  NOTICE: plugin.video.livetvonline v1.0.1: ------------------PARAMS------------------
17:54:08 T:140398956775168  NOTICE: plugin.video.livetvonline v1.0.1: --- Mode: 0
17:54:08 T:140398956775168  NOTICE: plugin.video.livetvonline v1.0.1: --- Url:
17:54:08 T:140398956775168  NOTICE: plugin.video.livetvonline v1.0.1: --- Name:
17:54:08 T:140398956775168  NOTICE: plugin.video.livetvonline v1.0.1: --- Thumbnail:
17:54:08 T:140398956775168  NOTICE: plugin.video.livetvonline v1.0.1: ------------------------------------------
17:54:08 T:140398956775168   ERROR: GetDirectory - Error getting /home/derzis/.kodi/addons/plugin.video.livetvonline/resources/skins/default
17:54:08 T:140398956775168   ERROR: EXCEPTION: XML File for Window is missing
17:54:08 T:140398956775168   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XML File for Window is missing
                                            Traceback (most recent call last):
                                              File "/home/derzis/.kodi/addons/plugin.video.livetvonline/default.py", line 60, in <module>
                                                dialog = gui_utils.loginDialog()
                                              File "/home/derzis/.kodi/addons/plugin.video.livetvonline/gui_utils.py", line 92, in loginDialog
                                                return LoginDialog('LoginDialog.xml', common.addon_path, 'default', '720p')
                                            RuntimeError: XML File for Window is missing
                                            -->End of Python script error report<--
17:54:09 T:140399766021888  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
17:54:09 T:140400171743168   ERROR: GetDirectory - Error getting plugin://plugin.video.livetvonline/
17:54:09 T:140400171743168   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.livetvonline/) failed
17:54:09 T:140398956775168  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by yokrysty** [comment]
deshide fisierul "gui_utils.py", cauta linia return LoginDialog('LoginDialog.xml', common.addon_path, 'default', '720p') si inlocuieste 'default' cu 'Default' si imi spui daca merge

**Comment by derzis** [comment]
merge perfect. Multumesc.

**Comment by yokrysty** [comment]
am uitat ca linux este case sensitive, my bad
