### ISSUE TITLE
4.0.19 could not load file

### ISSUE THREAD

**Issue by padme89911** [yokrysty/krysty-xbmc#36]
Daca nu am lasat un film sa se termine (ex. Am oprit sursa sau am dat stop) nu pot da play la altul (cel putin pana nu dar clear data sau restart la kodi). Keep up the good work :)

**Comment by yokrysty** [comment]
versiunea 0.4.x nu mai primeste update, foloseste versiunea 0.5.x
PS: instaleaza repository-ul pentru auto update
