### ISSUE TITLE
encryption key is not unique in android

### ISSUE THREAD

**Issue by catalinii** [yokrysty/krysty-xbmc#37]
Congratulations for the work on the plugin.

On Windows and MAC works good but I have some issues in Android.

After login in, entering the user and pw, the plugin works. After exiting and logging out the plugin does not work anymore.

On additional investigation it seems the user and password are getting corrupted after multiple logins and logouts. The reason is that uuid.uuid1() does not return the same uuid everytime.

In enc.py I have added the following line (at line 7):

log_utils.log("XXXX uuid %s pwd %s _key %s" % (uuid.uuid1(), _pwd, _key))

The output I got in android after logging in multiple times:

17:04:59 T:18446744072536346960  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid f0bdf1e8-c7e8-11e5-b666-8f7b761f2dbd pwd 8f..... _key '?D....'
17:06:34 T:18446744072530475528  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid 29d763d1-c7e9-11e5-b15d-bfb45f1f2596 pwd bf.... _key dk...
17:06:49 T:18446744072532679064  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid 3290ca17-c7e9-11e5-a399-b1d57083d09e pwd b1.... _key ?5...

This results in inability to login and see the list of channels and determines the plugin to thrown an exception:

17:06:55 T:18446744072532679064   ERROR: Traceback (most recent call last):
17:06:55 T:18446744072532679064   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.livetvonline/scraper.py", line 134, in getTVChannelsList
17:06:55 T:18446744072532679064   ERROR:     ul = parseDOM(html, 'ul', attrs={'class': 'sc_menu'})[0]
17:06:55 T:18446744072532679064   ERROR: IndexError: list index out of range

Thanks

**Comment by yokrysty** [comment]
i know there is a problem on android, but i didn't figure it out yet
sorry but that's not the problem

uuid.uuid1() returns (for example):
UUID('21aef70f-c87d-11e5-99b5-74e6e226b888')

i use only the last part (74e6e226b888), which is unique and constant
(notice the split('-')[-1], this code returns the last part of uuid)

below there are 10 iterations, pwd is always the same:
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: UUID: f5d42342-c87f-11e5-86db-158c250bd634
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 23691661137460
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: f5d47bba-c87f-11e5-ad9b-158c250bd634, pwd: 158c250bd634, md5: 071f37ac50f7d570c5049581e75222d7
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: UUID: f5d49a70-c87f-11e5-81ae-158c250bd634
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 23691661137460
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: f5d4b961-c87f-11e5-95de-158c250bd634, pwd: 158c250bd634, md5: 071f37ac50f7d570c5049581e75222d7
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: UUID: f5d4d242-c87f-11e5-92d9-158c250bd634
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 23691661137460
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: f5d4e75c-c87f-11e5-b180-158c250bd634, pwd: 158c250bd634, md5: 071f37ac50f7d570c5049581e75222d7
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: UUID: f5d4fd78-c87f-11e5-86e2-158c250bd634
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 23691661137460
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: f5d51782-c87f-11e5-8f4a-158c250bd634, pwd: 158c250bd634, md5: 071f37ac50f7d570c5049581e75222d7
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: UUID: f5d52ede-c87f-11e5-8345-158c250bd634
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 23691661137460
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: f5d54951-c87f-11e5-a84f-158c250bd634, pwd: 158c250bd634, md5: 071f37ac50f7d570c5049581e75222d7
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: UUID: f5d55a97-c87f-11e5-bf8d-158c250bd634
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 23691661137460
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: f5d69eeb-c87f-11e5-ba1d-158c250bd634, pwd: 158c250bd634, md5: 071f37ac50f7d570c5049581e75222d7
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: UUID: f5d70075-c87f-11e5-adb7-158c250bd634
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 23691661137460
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: f5d79642-c87f-11e5-8932-158c250bd634, pwd: 158c250bd634, md5: 071f37ac50f7d570c5049581e75222d7
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: UUID: f5d85457-c87f-11e5-87ec-158c250bd634
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 23691661137460
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: f5d8b307-c87f-11e5-9ddb-158c250bd634, pwd: 158c250bd634, md5: 071f37ac50f7d570c5049581e75222d7
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: UUID: f5d9086e-c87f-11e5-8c42-158c250bd634
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 23691661137460
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: f5d9636e-c87f-11e5-bcd0-158c250bd634, pwd: 158c250bd634, md5: 071f37ac50f7d570c5049581e75222d7
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: UUID: f5d9d5d9-c87f-11e5-8a29-158c250bd634
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 23691661137460
03:06:01 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: f5da0168-c87f-11e5-b244-158c250bd634, pwd: 158c250bd634, md5: 071f37ac50f7d570c5049581e75222d7
03:06:03 T:1368493560  NOTICE: plugin.video.livetvonline v1.0.2: XBMC/Kodi 14.2 (X11; Linux) plugin.video.livetvonline v1.0.2

**Comment by yokrysty** [comment]
hmm, from what is see on your log, is different every time, hmm, maybe depends on phone
please put this lines in enc.py and write the log:

for i in range(10):
    log_utils.log('UUID: ' + str(uuid.uuid1()))
    log_utils.log('NODE: ' + str(uuid.getnode()))
    log_utils.log('XXXX uuid: %s, pwd: %s, md5: %s' % (uuid.uuid1(), _pwd, hashlib.md5(_pwd).hexdigest()))

**Comment by yokrysty** [comment]
after some test it seems that after closing xbmc/kodi, and reopen, the uuid changes, this sucks :(

**Comment by catalinii** [comment]
First time I enter in the plugin:
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 297830d9-c885-11e5-8314-c93a1360c6a9
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 221251270395561
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 29797d78-c885-11e5-bf81-c93a1360c6a9, pwd: c93a1360c6a9, md5: b89e0c4eccdcc444b2d226d94a3b9f55
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 297992eb-c885-11e5-9210-c93a1360c6a9
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 221251270395561
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 2979aabd-c885-11e5-83dd-c93a1360c6a9, pwd: c93a1360c6a9, md5: b89e0c4eccdcc444b2d226d94a3b9f55
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 2979dcd1-c885-11e5-bef0-c93a1360c6a9
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 221251270395561
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 2979f5dc-c885-11e5-b670-c93a1360c6a9, pwd: c93a1360c6a9, md5: b89e0c4eccdcc444b2d226d94a3b9f55
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 297a08f5-c885-11e5-bd04-c93a1360c6a9
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 221251270395561
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 297a232b-c885-11e5-bce2-c93a1360c6a9, pwd: c93a1360c6a9, md5: b89e0c4eccdcc444b2d226d94a3b9f55
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 297a350f-c885-11e5-b325-c93a1360c6a9
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 221251270395561
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 297a730f-c885-11e5-af23-c93a1360c6a9, pwd: c93a1360c6a9, md5: b89e0c4eccdcc444b2d226d94a3b9f55
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 297a8c17-c885-11e5-bdd8-c93a1360c6a9
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 221251270395561
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 297aa2c0-c885-11e5-8a84-c93a1360c6a9, pwd: c93a1360c6a9, md5: b89e0c4eccdcc444b2d226d94a3b9f55
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 297ab4a3-c885-11e5-b106-c93a1360c6a9
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 221251270395561
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 297acda3-c885-11e5-bb09-c93a1360c6a9, pwd: c93a1360c6a9, md5: b89e0c4eccdcc444b2d226d94a3b9f55
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 297adf87-c885-11e5-84ac-c93a1360c6a9
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 221251270395561
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 297af630-c885-11e5-9c20-c93a1360c6a9, pwd: c93a1360c6a9, md5: b89e0c4eccdcc444b2d226d94a3b9f55
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 297b0814-c885-11e5-b102-c93a1360c6a9
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 221251270395561
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 297b211c-c885-11e5-b5ce-c93a1360c6a9, pwd: c93a1360c6a9, md5: b89e0c4eccdcc444b2d226d94a3b9f55
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 297b342e-c885-11e5-9577-c93a1360c6a9
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 221251270395561
11:43:15 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 297b50d1-c885-11e5-8e43-c93a1360c6a9, pwd: c93a1360c6a9, md5: b89e0c4eccdcc444b2d226d94a3b9f55
11:43:16 T:18446744072534297552  NOTICE: plugin.video.livetvonline v1.0.2: XBMC/Kodi 16.0-BETA5 (X11; Linux) plugin.video.livetvonline v1.0.2

Exiting the plugin and entering again I get:

11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 7f8cd80f-c885-11e5-94eb-1fc0f0022882
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 34913520855170
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 7f8d802e-c885-11e5-9654-1fc0f0022882, pwd: 1fc0f0022882, md5: 3879298ad8061d3fc29ab2ff807d88dc
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 7f8d9800-c885-11e5-a0b6-1fc0f0022882
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 34913520855170
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 7f8db966-c885-11e5-a2f1-1fc0f0022882, pwd: 1fc0f0022882, md5: 3879298ad8061d3fc29ab2ff807d88dc
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 7f8dd273-c885-11e5-8e0a-1fc0f0022882
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 34913520855170
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 7f8df16b-c885-11e5-ad64-1fc0f0022882, pwd: 1fc0f0022882, md5: 3879298ad8061d3fc29ab2ff807d88dc
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 7f8e0a75-c885-11e5-b44a-1fc0f0022882
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 34913520855170
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 7f8e2aa6-c885-11e5-8967-1fc0f0022882, pwd: 1fc0f0022882, md5: 3879298ad8061d3fc29ab2ff807d88dc
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 7f8e4023-c885-11e5-a087-1fc0f0022882
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 34913520855170
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 7f8e6051-c885-11e5-94a0-1fc0f0022882, pwd: 1fc0f0022882, md5: 3879298ad8061d3fc29ab2ff807d88dc
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 7f8e87a6-c885-11e5-a33a-1fc0f0022882
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 34913520855170
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 7f8f9773-c885-11e5-82a1-1fc0f0022882, pwd: 1fc0f0022882, md5: 3879298ad8061d3fc29ab2ff807d88dc
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 7f8fe62b-c885-11e5-8a44-1fc0f0022882
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 34913520855170
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 7f909305-c885-11e5-b71e-1fc0f0022882, pwd: 1fc0f0022882, md5: 3879298ad8061d3fc29ab2ff807d88dc
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 7f90bcba-c885-11e5-ac81-1fc0f0022882
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 34913520855170
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 7f90f130-c885-11e5-ba63-1fc0f0022882, pwd: 1fc0f0022882, md5: 3879298ad8061d3fc29ab2ff807d88dc
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 7f910a3d-c885-11e5-b421-1fc0f0022882
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 34913520855170
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 7f912219-c885-11e5-a978-1fc0f0022882, pwd: 1fc0f0022882, md5: 3879298ad8061d3fc29ab2ff807d88dc
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: UUID: 7f913191-c885-11e5-a4cc-1fc0f0022882
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: NODE: 34913520855170
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: XXXX uuid: 7f91470c-c885-11e5-9d61-1fc0f0022882, pwd: 1fc0f0022882, md5: 3879298ad8061d3fc29ab2ff807d88dc
11:45:40 T:18446744072532155384  NOTICE: plugin.video.livetvonline v1.0.2: XBMC/Kodi 16.0-BETA5 (X11; Linux) plugin.video.livetvonline v1.0.2


I agree you need another way of generating a unique key.

BTW, why don't you create a separate repository just with the code. I am thinking the EPG can be added also in kodi

**Comment by catalinii** [comment]
On the other side, if you rely on something that a "hacker" can get access to if he gets access on the system to see the user and password from the settings.xml, is not really better than leaving them plain text...

**Comment by yokrysty** [comment]
yeah i know its not a strong encryption, but i don't think its that weak
if the key is unique on each system, data cant be decrypted on other system

**Comment by catalinii** [comment]
yes I do ... but we should probably keep it maybe in english as other ppl might have some new ideas...

**Comment by yokrysty** [comment]
ok, but this plugin is meant for romanian peoples :)

i pushed the update without the encryption, just the base 64 encode
also uploaded the source code

about the EPG, I don't know what it is exactly, something, from RDS-RCS, is it paid?

**Comment by catalinii** [comment]
You have a point.

About epg, scraping port.ro?

**Comment by yokrysty** [comment]
oh, now i get it, from wikipedia Electronic program guides (EPGs) scheduling information for current and upcoming programming.

I am pretty sure port.ro offer paid APIs
maybe cinemagia.ro (http://www.cinemagia.ro/program-tv/vertical/)
or others... but I don't know if I need their permission for scraping.

I hope to find some other websites that have free APIs.

PS: the coding will take some time :)

**Comment by yokrysty** [comment]
EPG added in v1.0.4
right click on channel

**Comment by catalinii** [comment]
Hi,

With the new version I get the following error:
11:43:48 T:18446744072500816976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: ('invalid syntax', ('/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.livetvonline/tvguide.py', 61, 55, "            hours += soup.findAll('td', attrs={'class', 'ora'})\n"))
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.livetvonline/default.py", line 23, in <module>
                                                import common, enc, scraper, tvguide, gui_utils, log_utils
                                            SyntaxError: ('invalid syntax', ('/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.livetvonline/tvguide.py', 61, 55, "            hours += soup.findAll('td', attrs={'class', 'ora'})\n"))
                                            -->End of Python script error report<--
11:43:48 T:18446744072487168400   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.livetvonline/
11:43:48 T:18446744072487168400   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.livetvonline/) failed

Thanks

**Comment by yokrysty** [comment]
offf, there is a typo, attrs={'class', 'ora'} should be attrs={'class': 'ora'}, ':' instead of  ','
its weird that is workign on Windows,
also after I've fixed this typo, I've discovered other errors on Android, later this day I will send the update

**Comment by ursan2003** [comment]
Multumim pentru parental control

**Comment by ursan2003** [comment]
Merci inca odata manmerge snur versiunea 2in rest totul ok?sanatate examene femei?ce proiecte ai pe rol?eu sant in pana de idei momentanSuccesuri 

    On Sunday, 21 February 2016, 20:32, yokrysty <notifications@github.com> wrote:
 

 Closed #37.—
