### ISSUE TITLE
Ricght click non-existant in 990.ro

### ISSUE THREAD

**Issue by tyem88** [yokrysty/krysty-xbmc#38]
Salut, nu stiu daca e o problema cunoscuta sau nu, dar de la versiunea 0.5 nu se poate da click dreapta pe niciun serial si, implicit, nu se poate adauga la favorite. 
E o problema care nu a fost pe versiunile 0.4, nu e mare lucru dar totusi e destul de mult hastle sa cauti fiecare serial de fiecare data cand vrei sa vezi un episod, mai ales daca urmaresti mai multe.

**Comment by yokrysty** [comment]
am rezolvat in v0.5.5

**Comment by tyem88** [comment]
mersi pentru raspuns, si cu search merge stiu dar tot putin mai greu (mai ales daca esti de pe telecomanda (fara tastatura qwerty). Vad ca inca nu isi face update din repository banuiesc ca mai dureaza putin

**Comment by yokrysty** [comment]
apasa de mai multe ori pe check for updates, se gaseste pe bara din dreapta acolo unde instalezi addon-uri

**Comment by tyem88** [comment]
a mers, multumesc frumos
