### ISSUE TITLE
In versiunea noua nu se poate adauga un serial/film in lista "Favourites"

### ISSUE THREAD

**Issue by Extre76** [yokrysty/krysty-xbmc#39]
Salut. Mai exact in versiune 0.4.19 puteam sa navighez pana la denumirea serialului si sa-l adaug in lista de "Favourites". Acest lucru ma scutea sa accesez de fiecare data toate folderele pana la serialul pe care il doream. Cand ai un Raspberry care merge cum merge devine un pic agasant sa navigez de fiecare data pana la serial->episod. Avandu-l in "Favourites" era mai simplu, mai scuteam ceva timp ...

**Comment by yokrysty** [comment]
am rezolvat in v0.5.5
