### ISSUE TITLE
990. ro nu mai merge pe kodi

### ISSUE THREAD

**Issue by marieryro** [yokrysty/krysty-xbmc#40]
versiunea 0.4.19 nu mai merge, cam de doua zile. video link(s) not available este mesajul de eroare

**Comment by yokrysty** [comment]
versiunea 0.4.x nu mai primeste update-uri, foloseste 0.5.x
instaleaza repository-ul pentru autoupdates

**Comment by dab78** [comment]
Pai nici cea noua nu mai funcționează chiar daca am instalat si dezinstalat repository-ul. Nici in kodi nici un vidon kodi.

**Comment by zodrach** [comment]
functioneaza ultima versiune dar e o mica problema cred. Incerc sa urmaresc penultimul serial din Blacklist(Lady Ambrosia) si la fiecare din surse imi da " Resolver error ----- Unknown server error"

**Comment by yokrysty** [comment]
eroarea aceea este pentru serverul openload.co
am verificat toate serverele si acel episod nu mai exista pe nici unul din ele
plugin-ul functioneaza foarte bine, iti spune ca nu poate fi gasit ("stream file not available or removed")
in acest caz nu am ce face

**Comment by drdthebig** [comment]
Un cont pentru Live tv cum im fac?
Pe aplicatia de win imi spune ca nu se mai accepta clienti noi

**Comment by marieryro** [comment]
yokrysty - apreciez munca depusa , dar nu inteleg de ce versiunea 0.4.x nu mai primeste update? mie mi s-a parut mult mai buna decit ce e acum. subtitrare luata automat acolo unde exista, imagine mai buna....

**Comment by marieryro** [comment]
de asemenea serialele mai vechi nu mai merg in aceasta noua versiune... cred ca s-a cam dus 990... pacat era bun, ne intoarcem la torrente :)

**Comment by yokrysty** [comment]
aceasta versiune e mai buna din mai multe puncte de vedere, nu stiu pe ce baza faci tu comparatia
subtitrarea este luata automat pe serverele: superweb, openload si thevideo.me, daca exista
ce vrei sa spui prin imagine mai buna?
ce seriale mai vechi nu merg? poate nu exista pe nici un server.

**Comment by dab78** [comment]
Eu am încercat si pe r6s si minix 8h plus si himedia apar alte surse fara
superweb  si îmi dau eroare.
Pe 20 feb. 2016 1:58 PM, "yokrysty" <notifications@github.com> a scris:

**Comment by yokrysty** [comment]
din cate am vazut eu superweb a fost scos de cei de la 990
posteaza log-ul complet
spune-mi un nume de serial care nu iti merge

**Comment by dab78** [comment]
Vikings seria4 ep.1
Pe 20 feb. 2016 2:08 PM, "yokrysty" <notifications@github.com> a scris:

**Comment by yokrysty** [comment]
merge foarte bine si este disponibil pe toate serverele, openload si thevideo.me au si titrari in romana pentru el, vorbim de versiunea 0.5.6
daca nu postezi un log complet nu am cum sa te ajut

**Comment by dab78** [comment]
Ok  de unde i au 0.5.6 ? Ca am download at repository ul si l am instalat
in kodi . Are 05.6 in el ?
Pe 20 feb. 2016 2:13 PM, "yokrysty" <notifications@github.com> a scris:

**Comment by yokrysty** [comment]
daca inca nu apare in repository, mergi cu mous-ul pe bara din stanga si apasa check for updates

**Comment by dab78** [comment]
Te referi la kodi ?
Pe 20 feb. 2016 2:23 PM, "yokrysty" <notifications@github.com> a scris:

**Comment by yokrysty** [comment]
downloadezi repo de pe prima pagina, il instalezi in kodi, si cauti plugi-ul in acest repo

**Comment by dab78** [comment]
Multumesc , am instalat 0.5.6 si sursa cu subtitrari este openload.co. Eu
cautam superweb ul. Multumesc anticipat(DAB)
Pe 20 feb. 2016 4:14 PM, "yokrysty" <notifications@github.com> a scris:

**Comment by dab78** [comment]
Dar care este smecheria ca totusi nu toate merg.
Pe 20 feb. 2016 4:55 PM, "dan bencze" <benczedanalexandru@gmail.com> a
scris:

**Comment by yokrysty** [comment]
din cauza drepturile de autor video-urile sunt sterse de pe acele servere

**Comment by dab78** [comment]
Nasol păcat pentru munca depusă. Sper să mai apara alt site la fel de bun.
Succes in continuare si multumesc pentru eforturile depuse.
Pe 20 feb. 2016 5:29 PM, "yokrysty" <notifications@github.com> a scris:

**Comment by yokrysty** [comment]
ma indoiesc sa mai apara multi incearca sa scape de site-urile de genul asta, combatarea pirateriei

**Comment by dab78** [comment]
Fac presiune firmele mari producatoare de blu ray -uri. Mmmm o sa mi
trebuiasca un blu ray extern pt mini pc uri.
Pe 20 feb. 2016 9:22 PM, "yokrysty" <notifications@github.com> a scris:

**Comment by mikke75** [comment]
My merge nimic. Stream not available. Hai Cristi vezi ce poti face. Am cumparat 2 rasperry pi numai pt 990 Krysty.

**Comment by mikke75** [comment]
Vad ca folosesc mastervid

**Comment by yokrysty** [comment]
mastervid foloseste link-uri de la openload.co si thevideo.me, pe care deja le-am inclus

**Comment by dab78** [comment]
Dar superweb ce este cu el ?
Pe 21 feb. 2016 1:37 PM, "yokrysty" <notifications@github.com> a scris:

**Comment by yokrysty** [comment]
cred ca l-au anulat, nu stiu nu eu sunt proprietarul site-ului, eu doar am scris acest plugin pentru el

**Comment by yokrysty** [comment]
se pare ca mastervid are link-uri care nu sunt afisate in lista principala, il voi folosit si pe acela pentru a cauta link-urile video

**Comment by dab78** [comment]
Era cel mai bun
Pe 21 feb. 2016 1:40 PM, "yokrysty" <notifications@github.com> a scris:

**Comment by yokrysty** [comment]
era ilegal :)

**Comment by dab78** [comment]
Fi cel mai tare.  Succes

**Comment by yokrysty** [comment]
am incarcat versiunea 0.5.7, contine mai multe surse video
PS: Married with Childrens se poate viziona :)

**Comment by dab78** [comment]
Sa ti dea Dumnezeu sănătate.  Merge acum si  sursa este videomega. Ma
intrebam daca poți sa bagi si ok.ru. Am observat ca dintre toate sursele
este cea mai stabilă. Adică după ora 8 seara incep sa scartaie toate dar
ok.ru rămâne stabilă.  Oricum mare realizare , iti multumesc pentru efortul
depus .DAB
Pe 22 feb. 2016 01:26, "yokrysty" <notifications@github.com> a scris:

**Comment by yokrysty** [comment]
defapt ma folosesc si de mastervid, pe care se gasesc openload.co, openload.io si videomega, dar cum celelalte doua au fost gasite si din lista principala ramane doar videomega.
unde ai vazut ok.ru? da-mi un link care contine aceasta sursa?

**Comment by dab78** [comment]
Am vrut sa ma refer la alt siteuri care contin aceasta sursa. Filme online
2013 ,  voxfilmeonline pe hd4all (mini pc uri si egreat r6s).
Pe 22 feb. 2016 1:25 PM, "yokrysty" <notifications@github.com> a scris:

**Comment by yokrysty** [comment]
acest plugin cauta doar sursele de pe 990.ro
pe viitor cand voi avea timp voi face plugin-uri si pentru alte site-uri
plugin-ul pentru cinemaxx are ok.ru, dar acolo multe filme nu au nici o sursa

**Comment by dab78** [comment]
Ok. Oricum ma bucur ca update ul acum si l face singur kodi datorită
repository -ul pe care l ai facut.
Pe 22 feb. 2016 2:24 PM, "yokrysty" <notifications@github.com> a scris:

**Comment by sasa70** [comment]
In version 0.5.5 it worked nice enable titles on/off, but in version 0.5.7 I try to disable but without success

**Comment by yokrysty** [comment]
yes there is a problem, I solved it but i can't send the update just for that, until next update disable subtitle manually.

**Comment by mar1u50** [comment]
M-am updatat la v0.5.7
Din pacate se pare ca nu mai merge 990.ro
La toate, pluginul zice ca nu gaseste stream-ul.

Toata lumea pateste asta?

**Comment by yokrysty** [comment]
confirmca functioneaza, apasa clear cache in meniul principal

**Comment by mar1u50** [comment]
Cred ca am incercat. Dar mai incerc odata diseara. 

Multumesc

**Comment by mar1u50** [comment]
Testat de ex Deadpool.

Se poate alege:
1. videomega.tv - resolver error, stream file not available
2. openload.co - resolver error, stream file not available
3. videomega,tv - resolver error, stream file not available
4. videomega.tv - resolver error, stream file not available

Din browser, deadpool merge. Foloseste OK.ru. Merge si stream-ul de pe netu.tv

**Comment by mar1u50** [comment]
Am mai testat si altele (e.g. Black Mass [2015], Once upon a time).
Majoritatea au doar sursele videomega si openload.co - care nu merg (resolver error, stream file not available or removed)

**Comment by mar1u50** [comment]
Log:
22:38:39 4799.973633 T:1718612976  NOTICE: plugin.video.990 v0.5.7: Loading sqlite3 as DB engine, version: 3.9.2
22:38:39 4799.976562 T:1718612976  NOTICE: plugin.video.990: metahandler: Initializing MetaHandlers version: 2.9.0
22:38:39 4800.193848 T:1718612976  NOTICE: plugin.video.990: metahandler: Loading sqlite3 as DB engine version: 3.9.2
22:38:39 4800.197266 T:1718612976  NOTICE: plugin.video.990 v0.5.7: All tables have been successfully loaded.
22:38:39 4800.198242 T:1718612976  NOTICE: plugin.video.990 v0.5.7: ------------------PARAMS------------------
22:38:39 4800.198730 T:1718612976  NOTICE: plugin.video.990 v0.5.7: --- Mode: 1
22:38:39 4800.198730 T:1718612976  NOTICE: plugin.video.990 v0.5.7: --- Url: http://www.990.ro/filme-146540-Black-Mass-online-download.html
22:38:39 4800.198730 T:1718612976  NOTICE: plugin.video.990 v0.5.7: --- Name: Black Mass
22:38:39 4800.199219 T:1718612976  NOTICE: plugin.video.990 v0.5.7: --- Thumbnail: DefaultVideo.png
22:38:39 4800.199219 T:1718612976  NOTICE: plugin.video.990 v0.5.7: --- Video Type: movie
22:38:39 4800.199219 T:1718612976  NOTICE: plugin.video.990 v0.5.7: --- TV Show Name:
22:38:39 4800.199707 T:1718612976  NOTICE: plugin.video.990 v0.5.7: --- Year: 2015
22:38:39 4800.199707 T:1718612976  NOTICE: plugin.video.990 v0.5.7: --- Season:
22:38:39 4800.199707 T:1718612976  NOTICE: plugin.video.990 v0.5.7: --- Episode:
22:38:39 4800.200195 T:1718612976  NOTICE: plugin.video.990 v0.5.7: --- Episode Name:
22:38:39 4800.200195 T:1718612976  NOTICE: plugin.video.990 v0.5.7: --- IMDB ID:
22:38:39 4800.200684 T:1718612976  NOTICE: plugin.video.990 v0.5.7: --- TV Show Thumbnail:
22:38:39 4800.200684 T:1718612976  NOTICE: plugin.video.990 v0.5.7: ------------------------------------------
22:40:19 4900.076172 T:1718612976   ERROR: Traceback (most recent call last):
22:40:19 4900.076660 T:1718612976   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.990/resources/lib/resolvers/__init__.py", line 111, in resolve
22:40:19 4900.077637 T:1718612976   ERROR:     u = r.resolve(url)
22:40:19 4900.078125 T:1718612976   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.990/resources/lib/resolvers/videomega.py", line 36, in resolve
22:40:19 4900.078613 T:1718612976   ERROR:     r = int(urllib2.urlopen(r, timeout=15).headers['Content-Length'])
22:40:19 4900.078613 T:1718612976   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
22:40:19 4900.083008 T:1718612976   ERROR:     return opener.open(url, data, timeout)
22:40:19 4900.083496 T:1718612976   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 431, in open
22:40:19 4900.083496 T:1718612976   ERROR:     response = self._open(req, data)
22:40:19 4900.083984 T:1718612976   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 449, in _open
22:40:19 4900.083984 T:1718612976   ERROR:     '_open', req)
22:40:19 4900.084473 T:1718612976   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
22:40:19 4900.084473 T:1718612976   ERROR:     result = func(*args)
22:40:19 4900.084473 T:1718612976   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
22:40:19 4900.084961 T:1718612976   ERROR:     return self.do_open(httplib.HTTPConnection, req)
22:40:19 4900.085449 T:1718612976   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
22:40:19 4900.085449 T:1718612976   ERROR:     r = h.getresponse(buffering=True)
22:40:19 4900.085449 T:1718612976   ERROR:   File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
22:40:19 4900.089355 T:1718612976   ERROR:     response.begin()
22:40:19 4900.089844 T:1718612976   ERROR:   File "/usr/lib/python2.7/httplib.py", line 415, in begin
22:40:19 4900.090332 T:1718612976   ERROR:     version, status, reason = self._read_status()
22:40:19 4900.090332 T:1718612976   ERROR:   File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
22:40:19 4900.090820 T:1718612976   ERROR:     raise BadStatusLine(line)
22:40:19 4900.090820 T:1718612976   ERROR: BadStatusLine: ''
22:42:03 5003.583496 T:1958355504   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.990/?name=Black+Mass&url=http%3A%2F%2Fwww.990.ro%2F
filme-146540-Black-Mass-online-download.html&video_type=movie&mode=1&year=2015&thumbnail=DefaultVideo.png]
22:42:10 5010.305176 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=Kung+Fu+Panda+3&url=http%3A%2F%2Fwww.990.ro%2F
filme-65994-Kung-Fu-Panda-3-online-download.html&video_type=movie&mode=1&year=2016&thumbnail=DefaultVideo.png
22:42:10 5010.309570 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?url=http%3A%2F%2Fwww.990.ro%2F&thumbnail=DefaultFol
der.png&name=Clear+Cache&mode=96
22:42:10 5010.314941 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?url=http%3A%2F%2Fwww.990.ro%2F&thumbnail=%2Fhome%2F
osmc%2F.kodi%2Faddons%2Fplugin.video.990%2Fresources%2Fmedia%2Fsettingsicon.png&name=Settings&mode=95
22:42:10 5010.320801 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=Frozen+Fever&url=http%3A%2F%2Fwww.990.ro%2Ffil
me-260241-Frozen-Fever-online-download.html&video_type=movie&mode=1&year=2015&thumbnail=DefaultVideo.png
22:42:10 5010.326172 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=Joe+Dirt+2%3A+Beautiful+Loser&url=http%3A%2F%2
Fwww.990.ro%2Ffilme-250061-Joe-Dirt-2-Beautiful-Loser-online-download.html&video_type=movie&mode=1&year=2015&thumbnail=DefaultVideo.png
22:42:10 5010.331543 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=Narcopolis&url=http%3A%2F%2Fwww.990.ro%2Ffilme
-39430-Narcopolis-online-download.html&video_type=movie&mode=1&year=2015&thumbnail=DefaultVideo.png
22:42:10 5010.336914 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=The+5th+Wave&url=http%3A%2F%2Fwww.990.ro%2Ffil
me-221878-The-5th-Wave-online-download.html&video_type=movie&mode=1&year=2016&thumbnail=DefaultVideo.png
22:42:10 5010.342285 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=Step+Up+2%3A+The+Streets&url=http%3A%2F%2Fwww.
990.ro%2Ffilme-109954-Step-Up-2-The-Streets-online-download.html&video_type=movie&mode=1&year=2008&thumbnail=DefaultVideo.png
22:42:10 5010.347656 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=Daredevil&url=http%3A%2F%2Fwww.990.ro%2Ffilme-
34266-Daredevil-online-download.html&video_type=movie&mode=1&year=2003&thumbnail=DefaultVideo.png
22:42:10 5010.352539 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=The+Forest&url=http%3A%2F%2Fwww.990.ro%2Ffilme
-221944-The-Forest-online-download.html&video_type=movie&mode=1&year=2016&thumbnail=DefaultVideo.png
22:42:10 5010.357910 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=Ride+Along+2&url=http%3A%2F%2Fwww.990.ro%2Ffil
me-131747-Ride-Along-2-online-download.html&video_type=movie&mode=1&year=2016&thumbnail=DefaultVideo.png
22:42:10 5010.363281 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=Deadpool&url=http%3A%2F%2Fwww.990.ro%2Ffilme-5
2345-Deadpool-online-download.html&video_type=movie&mode=1&year=2016&thumbnail=DefaultVideo.png
22:42:10 5010.373047 T:1762563056 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=What+Women+Want&url=http%3A%2F%2Fwww.990.ro%2F
filme-56442-What-Women-Want-online-download.html&video_type=movie&mode=1&year=2000&thumbnail=DefaultVideo.png
22:42:10 5010.378418 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=Mommy&url=http%3A%2F%2Fwww.990.ro%2Ffilme-2253
57-Mommy-online-download.html&video_type=movie&mode=1&year=2014&thumbnail=DefaultVideo.png
22:42:10 5010.384277 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=Under+the+Tuscan+Sun&url=http%3A%2F%2Fwww.990.
ro%2Ffilme-46586-Under-the-Tuscan-Sun-online-download.html&video_type=movie&mode=1&year=2003&thumbnail=DefaultVideo.png
22:42:10 5010.391113 T:1762563056 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=Boychoir&url=http%3A%2F%2Fwww.990.ro%2Ffilme-8
0480-Boychoir-online-download.html&video_type=movie&mode=1&year=2014&thumbnail=DefaultVideo.png
22:42:10 5010.395996 T:1718612976 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.990/?name=Infinitely+Polar+Bear&url=http%3A%2F%2Fwww.990
.ro%2Ffilme-87278-Infinitely-Polar-Bear-online-download.html&video_type=movie&mode=1&year=2014&thumbnail=DefaultVideo.png

**Comment by yokrysty** [comment]
daca nu merg cateva resolvere nu inseamna ca nu merge plugin-ul
am testat Deadpool, in afara de openload, pentru ca a fost sters, sunt 3 surse videomega care merg, am facut resolver pentru ok.ru pentru alt plugin, dar nu l-am inclus si in asta pentru ca nu existau astfel de surse, il voi include pe viitor
PS: acest film are varianta din cinema si pararea mea ca este pacat sa te uiti la el la o calitate asa inferioara

**Comment by mar1u50** [comment]
Ciudat.
Dupa cum ai vazut eu am testat cele 3 surse videomega si nu au mers.

Nu nu vroiam sa ma uit la el - voi merge la Cinema. Era doar un test.

In general niciun film nu mai merge dupa ultimele modificari 990 (nu cred ca pluginul e de vina ci site-ul 990  care tot modifica una alta).

De fapt nu mai gasesc aproape niciun film care sa mearga.

**Comment by yokrysty** [comment]
pai asta este ciudat, ca la mine sunt foarte putine care nu merg si vad ca nu sunt alte persoane care sa raporteze probleme

**Comment by mar1u50** [comment]
poate este ceva specific osmc / kodi / 990.ro v 0.5.7

Eu am doua raspberry pi care ruleaza osmc - ambele cu exact aceeasi problema.

**Comment by yokrysty** [comment]
incearca kodi in loc de osmc

**Comment by dab78** [comment]
Eu  am minix 8 h plus si himedia octacore h8 si merg . Dar încearcă si prin
hd4all pt.android  poate iti merge.
Pe 9 mar. 2016 15:10, "mar1u50" <notifications@github.com> a scris:

**Comment by mar1u50** [comment]
Inercat si kodi de pe android.
Exact acelasi comportament ca si kodi de pe osmc.

**Comment by mar1u50** [comment]
Voua va merge de exemplu filmul "spotlight"?

**Comment by dab78** [comment]
Da sursa este videomega  si il vad prin vid on xbmc.
Pe 9 mar. 2016 19:15, "mar1u50" <notifications@github.com> a scris:

**Comment by yokrysty** [comment]
I've added version 0.5.8:
- fix for openload resolver
- added ok.ru resolver
- other bug fixes

**Comment by sasa70** [comment]
In version 0.5.5 it worked nice enable titles on/off, but in version 0.5.8 I try to disable but without success....

**Comment by luci84tm** [comment]
Salut,  se pare că  de ieri nu mai merge addon ul.. 
am versiune 0.5.8 pe ultima veriune de osmc.. 
eroarea care apare in kodi este:
# Error: stream source(s)  not available! 
au schimbat iară 990 ceva la site-ul lor?

**Comment by dab78** [comment]
Vezi ca s a updatat la 0.5.9. Si acum merge
Pe 24 mar. 2016 23:48, "luci84tm" <notifications@github.com> a scris:

**Comment by luci84tm** [comment]
da,  am observat. 
chiar după câteva minute de la postarea mea a apărut update-ul :) 
Mulțumesc mult!!

**Comment by luci84tm** [comment]
Am observat de cateva saptamani trailer-ele nu mai merg.
mai are cineva problema asta sau eu sunt un caz izolat ? :D
