### ISSUE TITLE
990 0.5.8

### ISSUE THREAD

**Issue by mihaip1948** [yokrysty/krysty-xbmc#41]
In Setup : actiunea enable/disable SUB nu merge !

**Comment by yokrysty** [comment]
poate ca nu sunt titrari disponibile, sunt doar cateva surse care au titrari (thevideo.me, openload, atat imi amintesc), celel adaugate nu vor avea asa de repede, iti recomand plugin-ul opensubtitles, tot in repository-ul meu

**Comment by mihaip1948** [comment]
Problema nu era legata de faptul ca sunt sau nu subtitrari !!!ci daca vreau sa le dezactivez din SETUP ... nu pot !!!
