### ISSUE TITLE
Trakt.tv library

### ISSUE THREAD

**Issue by tyem88** [yokrysty/krysty-xbmc#42]
Salut, 
vroiam doar sa te intreb daca ai in plan pe viitor sa integrezi library gen trakt.tv in add-on

**Comment by yokrysty** [comment]
poate daca imi permite timpul si daca nu voi lasa balta plugin-ul

**Comment by tyem88** [comment]
Lasa balta ca sa te ocupi de restul sau pur si simplu sa le lasi pe toate? ar fi pacat

**Comment by yokrysty** [comment]
ar fi pacat? de ce? eu nu am nici de castigat, nici de pierdut

**Comment by tyem88** [comment]
am crezut ca le faci pentru tine, doar ca le si imparti cu restul lumii. Si ma refeream mai mult la plug-in-ul livetvonline.ro fiindca aveam abonament. Si pe tv il folosesc doar prin kodi pe un android box.

**Comment by yokrysty** [comment]
da le fac pentru mine si prieteni, iar cu restul lumii le pot imparti mai tarziu (daca vreau)
pentru plugin-ul livetvonline.ro voi trimite rapid update-urile

**Comment by tyem88** [comment]
Ma bucur, cum am zis ma refeream doar la livetvonline, fiindca pentru seriale exista alternative, pentru livetv din romania nu prea :D
