### ISSUE TITLE
xbmc

### ISSUE THREAD

**Issue by kodiname** [yokrysty/krysty-xbmc#44]
Salut am o intrebare am incercat sa instalez acest plugin pe enigma 2 se instaleaza e ok dar cand vreau sa deschid livetvonline imi apare o eroare in schimb cinemaxx si video.990 functioneaza perfect. Doar livetvonline nu se deschide sa pot pune email-ul si parola. Eu pe enigma 2 am instalat kodidirect.
Poate reusesti sa faci un plugin pt enigma 2 este foarte simplu pt tine ...

**Comment by yokrysty** [comment]
am trimis o noua versiune, incearca sa vezi daca functioneaza
PS: data viitoare cand vorbesti despre eroare m-ar ajuta un log

**Comment by kodiname** [comment]
Salut acum am pus si versiunea 2.0.4 si tot la fel unde iti pot trimite logo pe email. Cred ca problema este ca pe enigma 2 nu am optiunea unde sa adaug emailul si parola daca as pune emailul si parola direct in fisier cred ca ar merge asta cred ca este problema.

**Comment by kodiname** [comment]
Daca este iti trimit un video poate asa iti da-i seama mai bine care ar fi problema..

**Comment by kodiname** [comment]
Salut uite scriu log...
Asa imi apare exact ca aici asta e KodiDirect vers 3.0.1 pe enigma 2
Dreambox 800 hd se v2 ....

This text is also in plugin/ KodiDirect/Tips.txt
Please translate with google translate-if needed.

Dieser Text ist auch in -Plugin-/KodiDirect/Tips.txt
Bitte übersetzen Sie mit Google Translate- wenn n.

Ce texte est lement dans le plugin /KodiDirect/Tips.txt
Sil vous platraduire avec google translate - si nssaire.
#############################################
IMPROVE EXECUTION SPEED
#############################################
(1) Use config->Wait time at the lowest setting
that your addons wil work fully(list look complete).
The default setting10 sec ok for the powerful boxes
for most addons. The slower boxes and some addons may
need higer settings.

(2) After selecting an item in the list - you will see
two spinners-one after the other. The lower spinner
means-the plugin.py code is executing. The upper
spinner means-the addon code is executing. The
wait time limit is for the plugin.py execution.

(3) After the wait time is over -you see an ERROR
info. You may then (1) try another item or (2) exit
from KodiDirect and find the file/tmp/e.log.
In this log -if you see a missing software as the 
cause of the error - find and install the addon.
If you do not understand the log - post it in the
support forum for help. If there is a crash log
-do the same.

(5) if the Parental Control PIN is set in the 
image - the adult addins are not visible.

(6) If the addon file /resurces/settings.xml had a
meta option - set it to false.

(7) Thumbpics make it slow. So if you want to make it 
faster set Config - Show thumbpics->No.

**Comment by kodiname** [comment]
Here in default-py sys.argv = ['/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.livestream/default.py', '18', '?plugin://plugin.video.livestream/?url=%2Flogin&mode=150&name=My+Channels&icon=%2Fusr%2Flib%2Fenigma2%2Fpython%2FPlugins%2FExtensions%2FKodiDirect%2Fplugins%2Fplugin.video.livestream%2Ficon.png']
Here in default-py sys.argv B= ['plugin://plugin.video.livestream/', '18', '?url=%2Flogin&mode=150&name=My+Channels&icon=%2Fusr%2Flib%2Fenigma2%2Fpython%2FPlugins%2FExtensions%2FKodiDirect%2Fplugins%2Fplugin.video.livestream%2Ficon.png']
Mode: 150
Name: My Channels
Event ID:None
Owner ID:None
Video ID:None
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.livestream/default.py", line 743, in <module>
    LOGIN()
  File "/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.livestream/default.py", line 544, in LOGIN
    response = urllib2.urlopen(req, body)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 438, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 521, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by yokrysty** [comment]
nu ma ajuta cu nimic ce ai lasat aici
