### ISSUE TITLE
990-resolver error

### ISSUE THREAD

**Issue by Futerix** [yokrysty/krysty-xbmc#45]
resolver error - note type objective has no atribute group. urmat de eroarea not available or removed.

asta e eroarea de apare la majoritatea serialelor, in special toate de mergeau openload,io acum nu mai merg, era cam cea mai folosita sursa de 990, restul nu merg sau cu putin noroc mai merge cate ceva

se poate rezolva te rog?

PS: ca reper , incercam sa vad how i met your mother sezonul 6

**Comment by yokrysty** [comment]
cunosc problema si am rezolvat-o pentru prieteni,
dar dupa cum am mai scris nu cred ca voi mai face update acestui plugin, cel putin nu curand

**Comment by Futerix** [comment]
Stiu ca nu ai nimic de castigat din acest plugin si poate nici timp dar eu unul as face o donatie pentru munca superba pe care o depui, pentru mine e un must in familie fiindca nu mai e nevoie de mine sa stau sa pun filme la tv fiindca o pot face singuri cei mici si sotia, e usor de folosit pe un raspberry pus pe tv, mai sunt si altele plugin-uri dar nu se compara cu al tau si in plus 990-ul e intern si se incarca rapid fata de altele externe care fac buffer.
E cea mai fain metoda existenta pentru tv si fara batai de cap, te rog sa nu abandona plugin-ul pentru public.
Ai adresa mea mai jos, daca se poate lasa-mi un mail fiindca nu gasesc nici o metoda sa-ti dau PM aici, pdamuj@gmail.com

PS: daca nu accepti donatii macar lasa-ma sa te cinstesc sau sa-ti umplu frigideru de bere ca vine vara si se face cald.

Mult spor si sper sa mai oferi suport.
