### ISSUE TITLE
Serverele si weekendul !

### ISSUE THREAD

**Issue by mihaip1948** [yokrysty/krysty-xbmc#46]
Buna Crysty ! romanii ti-au sugrumat total in weekend
serverele !!! practic imposibli sa pornesti un film si
asta se intampla de pe un calculator zdravan ... un 
server nou ceva ?

**Comment by yokrysty** [comment]
lmao, nu cred ca ai inteles, nu sunt serverele mele, eu doar am facut plugin-uri, nu am nici o legatura cu nici unul din site-uri

**Comment by mihaip1948** [comment]
Stiu ! asta ...scuze ! eu doar sugeram daca ai posibilitateasa te legi la altele sau sa adaugi ceva nou ... n-ar fi rau !

**Comment by yokrysty** [comment]
momentan nu, pentru ca, dupa cum am mai scris, nu voi mai trimite update-uri
poate peste un timp cand voi fi mai liber, daca lumea inca se arata interesata

**Comment by xploit00** [comment]
Cred ca foarte multa lume e interesata, si sa stii ca, chiar ai facut treaba foarte buna, e pacat sa renunti tocmai acum

**Comment by mihaip1948** [comment]
pai nu renunt ! constat doar ca din cand in candmai dau si eu in bara ... asta face viata mai diversa !

**Comment by mihaip1948** [comment]
Cum sa nu fie interesata ? a devenit pluginul national !!!
