### ISSUE TITLE
salut

### ISSUE THREAD

**Issue by qazwer1** [yokrysty/krysty-xbmc#47]
s-au schimbat serverele pentru 990

Poti sa imi spui unde sa modific ca sa le adaug pe cele noi?

Multumesc

**Comment by yokrysty** [comment]
poti sa fii mai exact?

**Comment by nykolai69** [comment]
Salut! Nu mai merg videourile de pe servarul openload, poti remedia problema?! Multumesc pt cea ce faci!

**Comment by yokrysty** [comment]
da stiu, openload fac schimbari foarte des pentru a impiedica plugin-urile de pe Kodi sa mai functioneze, am facut si eu modificarile necesare, dar nu le-am trimis public pentru ca s-ar putea sa nu dureze mult si sa modifice din nou ceva

**Comment by nykolai69** [comment]
Multumesc mult de tot pentru actualizare...merge super bine...inclusiv openload.io si openload.co....mersi multa inca o data pentru acualizare si pt. cea ce faci...TE SALUT CU RESPECT !!!
