### ISSUE TITLE
Domeniu sechestrat. 

### ISSUE THREAD

**Issue by psichokillah** [yokrysty/krysty-xbmc#48]
Salut. 
Cred ca poti inlatura suportul pentru 990.ro din moment ce domeniul tocmai a fost sechestrat.

**Comment by yokrysty** [comment]
interesant, ma intrebam cand se va intampla asta, pentru ca am vazut ca multe site-uri de genul au fost inchise

**Comment by yokrysty** [comment]
se pare ca doar domeniul a fost inchis, serverul este functional la http://89.40.16.50/

**Comment by Chiosc** [comment]
Mai e functional pluginul 990.ro?
De ieri seara nu-mi mai merge, sunt pe versiunea 0.5.11

**Comment by dantux** [comment]
kristy, unde ai modificat in plugin? Am re-instalat repository-ul dar tot nu merge.

**Comment by yokrysty** [comment]
pai nu mai merge, a mers doar o zi, se pare ca au inchis complet serverul

**Comment by dantux** [comment]
Păcat... a fost un add-on super. Merci încă o dată pentru tot ce-ai făcut până acum.
